name: GitHub Actions Sandbox

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Thursday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Sam it's Wednesday"
        if: ${{ env.DAY_OF_WEEK == 'Wednesday' }}
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Sam
  job_1:
    name: Upload File
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World, it's $DAY_OF_WEEK" > file.txt
      - uses: actions/upload-artifact@v2
        with:
          name: file
          path: file.txt
  job_2:
    name: Download File
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: file
      - run: cat file.txt
