name: GitHub Actions Sandbox

on:
  workflow_dispatch

env:
  foo: bar

jobs:
  runnerjob:
    runs-on: ubuntu-latest
    steps:
      - name: print os
        run: | 
          echo "The operating system is $env:RUNNER_OS."  
          echo "MY_RUNNER_OS=" + $RUNNER_OS >> "$GITHUB_ENV"
          echo "$MY_RUNNER_OS"
          echo "::set-output name=my_runner_os::${MY_RUNNER_OS}"
    outputs:
      my_runner_os: ${{ steps.runnerjob.outputs.my_runner_os }}
  foo-job-two:
    name: Another test job
    needs: runnerjob
    runs-on: ubuntu-latest
    steps:
      - name: Print out env variable from runnerjob
        run: echo "${{ needs.runnerjob.outputs.my_runner_os }}"
