name: GitHub Actions Sandbox

on:
  workflow_dispatch

env:
  foo: bar

jobs:
  if-Windows-else:
    runs-on: ubuntu-latest
    steps:
      - name: condition 1
        run: echo "The operating system is $env:RUNNER_OS."  
      - name: Set env var
        run: echo "MY_RUNNER_OS=" + $RUNNER_OS >> "$GITHUB_ENV"
      - name: Print os name
        run: echo "$MY_RUNNER_OS"
  foo-job-two:
    name: Another test job
    needs: if-Windows-else
    runs-on: ubuntu-latest
    steps:
      - name: Print out env variable from if-Windows-else
        run: echo "$env:MY_RUNNER_OS"
