name: GitHub Actions Sandbox

on:
  workflow_dispatch

env:
  foo: bar

jobs:
  runnerjob:
    name: runner_job
    runs-on: ubuntu-latest
    outputs:
      my_runner_os: ${{ steps.runner_job.outputs.my_runner_os }}
    steps:
      - name: print os
        run: | 
          echo "The operating system is " + $RUNNER_OS + "."  
          echo "MY_RUNNER_OS=" + $RUNNER_OS >> "$GITHUB_ENV"
          echo "MY_RUNNER_OS=" + $RUNNER_OS >> "$GITHUB_OUTPUT"
          echo "My runner os is " + $MY_RUNNER_OS + "."
  foo-job-two:
    name: Another test job
    needs: runnerjob
    runs-on: ubuntu-latest
    steps:
      - name: Print out env variable from runnerjob
        run: echo "${{ needs.runnerjob.outputs.my_runner_os }}"
