name: GitHub Actions Sandbox

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Wednesday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Sam it's Wednesday"
        if: ${{ env.DAY_OF_WEEK == 'Wednesday' }}
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Sam
