name: GitHub Actions Sandbox

on:
  workflow_dispatch

env:
  foo: bar

jobs:
  if-Windows-else:
    runs-on: macos-latest
    steps:
      - name: condition 1
        if: runner.os == 'Windows'
        run: echo "The operating system on the runner is $env:RUNNER_OS."
      - name: condition 2
        if: runner.os != 'Windows'
        run: echo "The operating system on the runner is not Windows, it's $RUNNER_OS."  
      - name: Step 1
        run: echo ("MY_RUNNER_OS=" + $RUNNER_OS) >> $env:GITHUB_ENV
      - name: Print branch name
        run: echo "${{ env.MY_RUNNER_OS }}"
  foo-job-two:
    name: Another test job
    runs-on: ubuntu-latest
    steps:
      - name: Print out env variable from foo-job
        run: echo echo "${{ env.MY_RUNNER_OS }}"
