name: GitHub Actions Sandbox

on:
  workflow_dispatch

env:
  foo: bar

jobs:
  jobone:
    name: job_one
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: "::debug::test debug message"
